### ISSUE TITLE
Nut sending wrong file...

### ISSUE THREAD

**Issue by Ronald-Diemicke** [blawar/nut#175] opened 2020-05-22 23:45 UTC
This may be related to another ticket... but I noticed that when I request something with Tinfoil 8, I'm getting an issue where the wrong file gets sent for updates...
[22/May/2020 18:22:55] "HEAD /api/download/01006F8002326800/Animal%20Crossing%20New%20Horizons%5B01006F8002326800%5D%5BUS%5D%5Bv458752%5D%5BCR-14%5D.nsz HTTP/1.1" 200 -
[22/May/2020 18:22:55] "GET /api/download/01006F8002326800/Animal%20Crossing%20New%20Horizons%5B01006F8002326800%5D%5BUS%5D%5Bv458752%5D%5BCR-14%5D.nsz HTTP/1.1" 206 -

I'm wondering if the character encoding is messing up which file it's picking up because I have multiple updates in the same directory. Any ideas?

**Comment by Gardosen** [comment] 2020-07-17 18:58
I can confirm this issue.
this does not only affect updates, it affects also normal base versions and also games where xci,nsp and nsz exist. (a full stash reference for example)

this even breaks the entire download/install process, if there is also an xci file existing.

**Comment by introkun** [comment] 2020-11-04 21:15
Could you please provide more details to reproduce the issue?

**Comment by blawar** [comment] 2020-11-04 21:20
The issue is likely that nsp.getTitleById() scans the files database for the title id, and not match the format that the client is requesting:

https://github.com/blawar/nut/blob/master/server/controller/api.py#L223

can be fixed by looking at the extension is is being requested by tinfoil, and only serving files that match that type of file (nsz/nsp can be mixed, and xci/xcz can be mixed).

**Comment by introkun** [comment] 2020-11-17 16:49
Duplicates #165

**Closed by introkun** 2020-11-17 16:49 UTC
Labels: bug, cannot reproduce
