### ISSUE TITLE
Nut 2.6/2.7 crashing on launch

### ISSUE THREAD

**Issue by squallscloud** [blawar/nut#174] opened 2020-05-22 05:35 UTC
I'm able to launch it, it then takes a few seconds then flashes a whole page of text too quickly for me to read before it closes everything, the white page doesn't even load up at all. I'm at a loss.
On windows 10 with updated USB drivers.

**Comment by Gardosen** [comment] 2020-07-22 10:35
you should start it over cmd, then the error message won't dissapear.

let me know what it says and we can check what the problem is.

**Comment by Kinghk1** [comment] 2020-10-01 08:53
hi thanx for the great app, i am having the same issue mentioned all the nut.exe version are crashing on execution. i started having this issue after reinstalling a fresh version of win10, sorry i have little knowledge in python and i need ur help, i took a fone burst shot so i can read the crashing message since it it disappears fast,

Traceback (most recent call lost):
File "server.py", line 31, in <module>
ImportErrorr : DLL load failed: The specified module could not be found.
[1984] Failed to execute scipt server

**Comment by introkun** [comment] 2020-10-24 21:39
Please open 'cmd' (Windows-Run-cmd.exe) and execute a script from the black screen. It will give you more context.

**Comment by introkun** [comment] 2020-10-30 15:51
@squallscloud any updates?
@blawar maybe close the issue?

**Closed** 2020-10-30 15:55 UTC
